# Site Settings
lang: en
title: Disabled
tagline: Forex Trading Strategies, Risk Management & Market Success
email: zethgroup at gmail dot com
description: >
  Master Forex strategies, practice risk management, and confidently navigate dynamic markets with Day Trading Ltd. Your guide to successful currency exchange
baseurl: ""
url: "https://www.daytrading.ltd"
permalink: /:categories/:title
#favicon: /path/to/favicon.png
#gh_sponsor: gannintegral
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

google_analytics: G-PBQSEQ50D3

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "GannIntegral"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
